import { createClientFromRequest } from 'npm:@base44/sdk@0.8.21';

const SEED_DATA = [
  { state_name: "Alabama", state_abbrev: "AL", tax_sale_fee_cap: "No specific cap on surplus finder fees", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Former owner gets written notice of surplus. Redemption period: None. Relatively unregulated for finders.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Alaska", state_abbrev: "AK", tax_sale_fee_cap: "Surplus paid to former owners per statute", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "No specific cap", sheriff_sale_fee_cap_pct: null, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Small population, limited volume. 30-day redemption period. Less regulated.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Arizona", state_abbrev: "AZ", tax_sale_fee_cap: "No specific surplus finder cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "30%", sheriff_sale_fee_cap_pct: 30, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration for UCP", waiting_period: "2 years before fee allowed (UCP)", waiting_period_days: null, pi_attorney_required: true, pi_attorney_detail: "YES — PI license required for UCP", key_notes: "High 30% cap but PI license required. PI license is easy in AZ — no experience needed, ~$74 fee, just need sponsor. Dept issues separate check to finder.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Arkansas", state_abbrev: "AR", tax_sale_fee_cap: "Surplus goes to former owners; 1 year to claim after deed recordation", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "No specific cap", sheriff_sale_fee_cap_pct: null, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Former owners paid remaining funds after Commissioner of State Lands. Less regulated.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "California", state_abbrev: "CA", tax_sale_fee_cap: "$2,500 or 5% whichever is GREATER (tax sale surplus)", tax_sale_fee_cap_pct: 5, sheriff_sale_fee_cap: "10% (UCP)", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration (but must file docs)", waiting_period: "Cannot contract once business notifies SCO of transfer", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Very finder-friendly once you follow guidelines. CA sends commission directly to finder. County probated estates have NO fee cap. Must file employee list with state. 10% cap for state UCP; different rules for county tax surplus.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Colorado", state_abbrev: "CO", tax_sale_fee_cap: "20% (foreclosure surplus, after waiting periods)", tax_sale_fee_cap_pct: 20, sheriff_sale_fee_cap: "No specific cap (after waiting period)", sheriff_sale_fee_cap_pct: null, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "VOID first 6 months (public trustee) + first 2 years (state treasurer)", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "HB16-1090: Contracts void during public trustee custody (6 mo) AND first 2 years of state treasurer custody. List costs $305. 500K+ names.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Connecticut", state_abbrev: "CT", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Simple rules. Contract must list property ID, value, fee %, and net amount to owner. Notarized contract required. Can get POA and state sends check to finder.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Delaware", state_abbrev: "DE", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "Lesser of 10% or $1,000", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "Registration required", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Very low effective cap — may not be profitable for small claims. $1,000 max severely limits earnings.", hassle_rating: 4, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "District of Columbia", state_abbrev: "DC", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "2 years", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Limited volume. Follows Uniform Unclaimed Property Act provisions.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Florida", state_abbrev: "FL", tax_sale_fee_cap: "12% (foreclosure/tax deed surplus per Statute 45.033)", tax_sale_fee_cap_pct: 12, sheriff_sale_fee_cap: "20% (state UCP)", sheriff_sale_fee_cap_pct: 20, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "YES — must be PI, CPA, or Attorney (UCP)", waiting_period: "None for UCP", waiting_period_days: null, pi_attorney_required: true, pi_attorney_detail: "YES — PI/CPA/Attorney for state UCP", key_notes: "UCP: Must be PI/CPA/Attorney or partner with one. $2B+ held. Surplus: 12% cap on assignee but recovery companies add \"consultation fees.\" Court motions required for surplus — practically needs attorney.", hassle_rating: 4, remote_friendly: false, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Georgia", state_abbrev: "GA", tax_sale_fee_cap: "5% (tax sale overages)", tax_sale_fee_cap_pct: 5, sheriff_sale_fee_cap: "10% (state UCP)", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "YES — CDR registration (UCP)", waiting_period: "24 months (UCP)", waiting_period_days: null, pi_attorney_required: true, pi_attorney_detail: "YES — GA-licensed attorney for tax overages", key_notes: "Very strict. Tax overages: only GA attorneys can charge fees. UCP: 10% cap, CDR registration, POA not recognized. SB 403 (2026): 25-year escheatment, data-matching for auto-returns under $500. Not finder-friendly.", hassle_rating: 5, remote_friendly: false, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Hawaii", state_abbrev: "HI", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "25%", sheriff_sale_fee_cap_pct: 25, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "High cap at 25%. Hi. Stat. § 523A-25. Limited volume due to population but good margins.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Idaho", state_abbrev: "ID", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Idaho and Kansas bar using info from state websites for commercial gain. Small market.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Illinois", state_abbrev: "IL", tax_sale_fee_cap: "Limited surplus generation", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "Registration required", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "\"Finder laws not good\" per industry experts. Better to search other states. State discourages finder activity.", hassle_rating: 4, remote_friendly: false, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Indiana", state_abbrev: "IN", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "24 months (UCP)", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "IC 32-34-1-46: 10% cap or $50 whichever is greater. Contracts void if entered within 24 months of delivery to AG. $350M+ held. Ads must state fee limits.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Iowa", state_abbrev: "IA", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Follows standard Uniform Unclaimed Property Act. Moderate volume.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Kansas", state_abbrev: "KS", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "15%", sheriff_sale_fee_cap_pct: 15, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "Registration required", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Kan. Stat. § 58-3968. Bars using state website info for commercial gain — need separate list. $500 penalty for misuse.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Kentucky", state_abbrev: "KY", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Standard UCP provisions. Moderate volume.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Louisiana", state_abbrev: "LA", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "Capped (varies)", sheriff_sale_fee_cap_pct: null, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Louisiana limits finder fees. Less regulated than some. Check current statutes for exact cap.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Maine", state_abbrev: "ME", tax_sale_fee_cap: "Limited surplus generation", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Small market. Standard UCP provisions.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Maryland", state_abbrev: "MD", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "NO CAP", sheriff_sale_fee_cap_pct: null, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "24 months before fees allowed", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "One of the BEST states for finders — no fee cap at all. Just a 24-month waiting period. Property held indefinitely, never escheats.", hassle_rating: 1, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Massachusetts", state_abbrev: "MA", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "2 years after property presumed abandoned", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "960 Mass. Reg. § 4.06. Written agreement with full disclosure required. Cannot enter agreement within first 2 years.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Michigan", state_abbrev: "MI", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "3-year dormancy period before state receives property. Standard provisions.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Minnesota", state_abbrev: "MN", tax_sale_fee_cap: "Limited surplus generation", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Standard UCP. Limited surplus fund opportunities from tax sales.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Mississippi", state_abbrev: "MS", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Standard UCP provisions. Moderate market.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Missouri", state_abbrev: "MO", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Standard UCP provisions. Large population = decent volume.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Montana", state_abbrev: "MT", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Small market. Standard UCP provisions.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Nebraska", state_abbrev: "NE", tax_sale_fee_cap: "Limited surplus generation", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Standard UCP. Limited tax sale surplus.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Nevada", state_abbrev: "NV", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "List available. Standard UCP provisions. Good volume from Las Vegas area.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "New Hampshire", state_abbrev: "NH", tax_sale_fee_cap: "Surplus goes to former owner; municipality files interpleader within 60 days", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Municipality must file interpleader within 60 days of settlement. Small market.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "New Jersey", state_abbrev: "NJ", tax_sale_fee_cap: "Court motion required for foreclosure surplus", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "20% (after 24 months); 35% (before state transfer)", sheriff_sale_fee_cap_pct: 20, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state UCP registration", waiting_period: "24 months for 20% cap", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "Recommended for surplus (court filings)", key_notes: "NJ R. 4:64-3 for surplus motions. 35% if contract signed before transfer to state (rare). 20% after 24 months. Court process for foreclosure surplus.", hassle_rating: 3, remote_friendly: false, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "New Mexico", state_abbrev: "NM", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Standard UCP provisions. Small-moderate market.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "New York", state_abbrev: "NY", tax_sale_fee_cap: "Court motion required for foreclosure surplus", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "15%", sheriff_sale_fee_cap_pct: 15, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration but must follow Comptroller procedures", waiting_period: "None specified for UCP", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No for UCP; recommended for surplus", key_notes: "N.Y. Aband. Prop. § 1416. Agreement must disclose owner can claim free from Comptroller. Must be notarized. State sends check in claimant name to finder. Dollar amounts not on list.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "North Carolina", state_abbrev: "NC", tax_sale_fee_cap: "20% for surplus funds", tax_sale_fee_cap_pct: 20, sheriff_sale_fee_cap: "20% or $1,000 (whichever is LESS)", sheriff_sale_fee_cap_pct: 20, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "YES — licensed PI + annual registration ($100)", waiting_period: "24 months", waiting_period_days: null, pi_attorney_required: true, pi_attorney_detail: "YES — PI license mandatory", key_notes: "Must be NC-licensed PI. N.C.G.S. § 116B-78. Agreements must be notarized by PI. $1,000 cap on most property makes it very low margin. Surplus funds get 20% cap without $1,000 limit.", hassle_rating: 5, remote_friendly: false, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "North Dakota", state_abbrev: "ND", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Very small market. Standard UCP provisions.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Ohio", state_abbrev: "OH", tax_sale_fee_cap: "No specific county surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "YES — state certification (background check, fingerprints, references)", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Thorough vetting: fingerprints (state+federal if out-of-state), 2 reference letters, color photo. Free registration except fingerprint costs. County lists often have no fee limits. Good market.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Oklahoma", state_abbrev: "OK", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "15%", sheriff_sale_fee_cap_pct: 15, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "Registration required", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Okla. Stat. tit. 60 § 674.1. Straightforward process. 15% is decent margin.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Oregon", state_abbrev: "OR", tax_sale_fee_cap: "Limited surplus generation", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Standard UCP. Limited tax sale surplus opportunities.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Pennsylvania", state_abbrev: "PA", tax_sale_fee_cap: "Governed by county tax claim bureaus", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "15% (may drop to 10%)", sheriff_sale_fee_cap_pct: 15, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "YES — Certificate from PA Treasury (background check)", waiting_period: "None specified for tax surplus", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "PENDING SB 1201: drop to 10%, national background check, online finder database. Finder list $300+tax. 450K+ names. Payments go to claimant only. Must include cert # on forms. County surplus rules vary.", hassle_rating: 3, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Rhode Island", state_abbrev: "RI", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "Pending legislation (H-7569)", sheriff_sale_fee_cap_pct: null, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "H-7569 bill introduced 2024 to cap finder fees. Currently less regulated. Check current status.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "South Carolina", state_abbrev: "SC", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "15% (criminal misdemeanor if exceeded)", sheriff_sale_fee_cap_pct: 15, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "Registration required", waiting_period: "24 months", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "S.C. Stat. § 27-18-360. Exceeding 15% is a criminal misdemeanor (fine or imprisonment). SC Family Privacy Act prohibits commercial solicitation using state data. Must provide written assurance list won't be used commercially.", hassle_rating: 4, remote_friendly: false, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "South Dakota", state_abbrev: "SD", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "25%", sheriff_sale_fee_cap_pct: 25, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "S.D. Stat. § 43-41B-36. High 25% cap. Small market but good margins.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Tennessee", state_abbrev: "TN", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10% (or $50 whichever is greater)", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "YES — PI license required", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: true, pi_attorney_detail: "YES — PI license", key_notes: "TCA 66-29-122: all contracts must be approved by Unclaimed Property Division. PI license required from TN Private Investigation and Polygraph Commission. Payments go to owner; finder collects separately.", hassle_rating: 4, remote_friendly: false, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Texas", state_abbrev: "TX", tax_sale_fee_cap: "Lesser of 25% or $1,000 (tax overages)", tax_sale_fee_cap_pct: 25, sheriff_sale_fee_cap: "10% (UCP)", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: true, registration_detail: "YES — PI license + sales tax permit (UCP)", waiting_period: "Tax surplus: 2 years before county distributes", waiting_period_days: null, pi_attorney_required: true, pi_attorney_detail: "YES — PI license for UCP; attorney for tax overages", key_notes: "Very restricted. Must be licensed PI with TX DPS for UCP. Tax overages: only attorneys can collect fees. Assignment of rights legal but heavily regulated by TX Property Tax Code. $1,000 cap on tax overages is very limiting.", hassle_rating: 5, remote_friendly: false, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Utah", state_abbrev: "UT", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "No specific cap", sheriff_sale_fee_cap_pct: null, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No state registration", waiting_period: "24 months", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "No fee cap mentioned in statute, but 24-month waiting period. POA must be separate from contract. Treasury pays owner/heir only. Finder must get claim status from client.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Vermont", state_abbrev: "VT", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Very small market. Standard UCP provisions.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Virginia", state_abbrev: "VA", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Standard UCP provisions. Good volume from Northern Virginia/DC metro area.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Washington", state_abbrev: "WA", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Standard UCP. Good volume from Seattle metro.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "West Virginia", state_abbrev: "WV", tax_sale_fee_cap: "Surplus goes to former owner per statute", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Former owner entitled to surplus above taxes/penalties/interest/fees/costs. WV Cash Now program auto-returns small amounts. Small market.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Wisconsin", state_abbrev: "WI", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "20%", sheriff_sale_fee_cap_pct: 20, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "20% cap. List available for ~$6. People reluctant to pay 20% — industry suggests offering lower rates. Decent market.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" },
  { state_name: "Wyoming", state_abbrev: "WY", tax_sale_fee_cap: "No specific surplus cap", tax_sale_fee_cap_pct: null, sheriff_sale_fee_cap: "10%", sheriff_sale_fee_cap_pct: 10, tax_sale_filing_method: "administrative", sheriff_sale_filing_method: "court_motion", registration_required: false, registration_detail: "No specific registration", waiting_period: "None specified", waiting_period_days: null, pi_attorney_required: false, pi_attorney_detail: "No", key_notes: "Smallest population state. Very small market. Standard UCP provisions.", hassle_rating: 2, remote_friendly: true, legal_disclaimer: "Laws change frequently. Verify current requirements with state/county authorities before operating. This is not legal advice.", last_updated: "2026-03-20" }
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return Response.json({ error: 'Forbidden: Admin access required' }, { status: 403 });
    }

    // Delete all existing records and reseed
    const existing = await base44.asServiceRole.entities.StateCompliance.list();
    for (const record of existing) {
      await base44.asServiceRole.entities.StateCompliance.delete(record.id);
    }

    // Bulk create in batches of 10
    let created = 0;
    for (let i = 0; i < SEED_DATA.length; i += 10) {
      const batch = SEED_DATA.slice(i, i + 10);
      await base44.asServiceRole.entities.StateCompliance.bulkCreate(batch);
      created += batch.length;
    }

    return Response.json({ 
      success: true, 
      message: `Successfully seeded ${created} state compliance records.`,
      count: created
    });

  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});